spring:
  application:
    name: messenger_v1

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/${MYSQL_DATABASE:messenger_v1}?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&socketTimeout=30000"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${MYSQL_USERNAME:admin}
    password: ${MYSQL_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

integration:
  minio:
    access-key: admin
    secret-key: admin@2024
    url: http://localhost:9000

server:
  port: 8081
  servlet:
    context-path: /api/v1
