name: messenger_v1

services:
  mysql:
    image: mysql:8.0.31
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=messenger_v1
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -u$${MYSQL_USER} -p$${MYSQL_PASSWORD}']
      interval: 5s
      timeout: 5s
      retries: 10
    restart: on-failure
    ports:
      - 3307:3306
    volumes:
      - ./mysql_data:/var/lib/mysql